const ALIEN_IN_ROWS = 3;
const ALIEN_IN_COLS = 6;
const NUM_ALIEN = ALIEN_IN_ROWS * ALIEN_IN_COLS;
const ALIEN_VALUE = 1;
const ALIEN_WIDTH = 20;
const ALIEN_HEIGHT = 20;
const ALIEN_PADDING = 30;
const ALIEN_MATRIX_WIDTH = (ALIEN_IN_COLS - 1) * (ALIEN_PADDING + ALIEN_WIDTH);
const ALIEN_MATRIX_HEIGHT = (ALIEN_IN_ROWS - 1) * (ALIEN_PADDING + ALIEN_HEIGHT);
const GAME_WIDTH = ALIEN_MATRIX_WIDTH + 73;
const GAME_HEIGHT = ALIEN_MATRIX_HEIGHT + 250;
const ALIEN_MATRIX_POS = GAME_WIDTH/2 - ALIEN_MATRIX_WIDTH/2;
const CANNON_0 = 20;
const CANNON_HEIGHT = 50;
const CANNON_WIDTH = 50;
const EDGE = 6;
const LIMITH = GAME_HEIGHT - EDGE;
const LIMITW = GAME_WIDTH - ALIEN_WIDTH - EDGE;
const EDGE_RIGHT = GAME_WIDTH - CANNON_WIDTH - CANNON_0;
const PLAYER_POS_X = GAME_WIDTH/2 - CANNON_WIDTH/2;
const PLAYER_POS_Y = 350 - CANNON_HEIGHT;
const ALIEN_SHOTS_PER_MINUTE = 50;
const MS_PER_FRAME = 16;
const LASER_SPEED = 3;
const GAME_OVER = "GAME OVER";
const GAME_NAME = "SPACE INVADERS";
const GAME_HELP = "PC: arrow keys (left and right) to move the defender, spacebar key to shoot. Mobile: touch and move, tap to shoot";
const GAME_WIN = "You WIN!";
const SCORE = "SCORE: ";
const BTN_PLAY_LABEL = "PLAY";
const BTN_AGAIN_LABEL = "PLAY AGAIN";

export default {
    ALIEN_IN_ROWS,
    ALIEN_IN_COLS,
    NUM_ALIEN,
    ALIEN_VALUE,
    ALIEN_WIDTH,
    ALIEN_HEIGHT,
    ALIEN_PADDING,
    ALIEN_MATRIX_WIDTH,
    ALIEN_MATRIX_HEIGHT,    
    GAME_WIDTH,
    GAME_HEIGHT,
    ALIEN_MATRIX_POS,
    CANNON_0,
    CANNON_HEIGHT,
    CANNON_WIDTH,
    EDGE,
    LIMITH,
    LIMITW,
    EDGE_RIGHT,
    PLAYER_POS_X,
    PLAYER_POS_Y,
    ALIEN_SHOTS_PER_MINUTE,
    MS_PER_FRAME,
    LASER_SPEED,
    GAME_OVER,
    GAME_NAME,
    GAME_HELP,
    GAME_WIN,
    SCORE,
    BTN_PLAY_LABEL,
    BTN_AGAIN_LABEL,
};